# Generated by Django 3.1.5 on 2021-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
