# Generated by Django 3.1.5 on 2021-06-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210628_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
